### ISSUE TITLE
Hugo Could not render org

### ISSUE THREAD

**Issue by tianheg** [niklasfasching/go-org#99] opened 2023-03-09 16:25 UTC
This error cannot be reproduced with certainty.

a minimal reproducible example: https://github.com/tianheg/hugo-render-org-error , use hugo v0.111.1

Errors like:

```sh
Could not render org: could not write output: runtime error: invalid memory address or nil pointer dereference. Using unrendered content.
```

or

```sh
Could not render org: could not write output: runtime error: unsafe.String: len out of range. Using unrendered content.
```

Error from Hugo [source code](https://github.com/gohugoio/hugo/blob/9af78d11003ed22b6281e47e1ac19568cf1cca81/markup/org/convert.go#L65).

I don't understand Golang. I post this error to [Hugo Forum](https://discourse.gohugo.io/t/hugo-could-not-render-org/42932/9). Thanks for @jmooring and @kaushalmodi 's help. I came here, keep looking for help.

**Comment by niklasfasching** [comment] 2023-03-12 10:39
D'oh! Fixed in https://github.com/niklasfasching/go-org/commit/5464ab3/ (couldn't reproduce the second error, but I'm assuming it's caused by the same race condition)

corresponding PR to update go-org in hugo https://github.com/gohugoio/hugo/pull/10824

**Closed by niklasfasching** 2023-03-12 10:39 UTC

**Comment by tianheg** [comment] 2023-03-14 01:27
Thank you very much! This problem has been bothering me for a long time.
